MEALS = [
 {"id":"teriyaki-chicken","name":"Chicken Teriyaki Bowl","description":"Glossy soy-ginger chicken with rice, cucumber and sesame.","time":25,"difficulty":"Easy","cost":2.8,"cuisine":"Asian","tags":["High Protein","Quick","Easy"],"ingredients":[["chicken breast",300,"g"],["rice",160,"g"],["cucumber",1,"unit"],["soy sauce",30,"ml"],["ginger",15,"g"],["garlic",2,"cloves"],["sesame",10,"g"]],"image":"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=85"},
 {"id":"arrabbiata","name":"Pasta Arrabbiata","description":"Spicy tomato pasta with garlic, chilli and parmesan.","time":20,"difficulty":"Easy","cost":1.75,"cuisine":"Italian","tags":["Cheap","Vegetarian","Quick"],"ingredients":[["pasta",180,"g"],["tomatoes",300,"g"],["garlic",2,"cloves"],["chilli flakes",2,"g"],["parmesan",30,"g"],["olive oil",15,"ml"]],"image":"https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=1200&q=85"},
 {"id":"salmon-poke","name":"Salmon Poke Bowl","description":"Salmon, rice, avocado, cucumber and edamame with sesame-soy dressing.","time":25,"difficulty":"Easy","cost":4.9,"cuisine":"Asian","tags":["High Protein","Healthy"],"ingredients":[["salmon",250,"g"],["rice",160,"g"],["avocado",1,"unit"],["cucumber",1,"unit"],["edamame",150,"g"],["soy sauce",25,"ml"],["sesame",10,"g"]],"image":"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=85"},
 {"id":"shakshuka","name":"Green Shakshuka","description":"Eggs baked into herby spinach with feta and warm bread.","time":30,"difficulty":"Easy","cost":2.2,"cuisine":"Mediterranean","tags":["Healthy","Vegetarian","One-Pot"],"ingredients":[["eggs",4,"unit"],["spinach",250,"g"],["feta",100,"g"],["onion",1,"unit"],["garlic",2,"cloves"],["bread",200,"g"],["olive oil",15,"ml"]],"image":"https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=1200&q=85"},
 {"id":"chicken-fajitas","name":"Chicken Fajitas","description":"Smoky peppers and chicken with lime, tortillas and avocado.","time":25,"difficulty":"Easy","cost":3.1,"cuisine":"Mexican","tags":["High Protein","Quick"],"ingredients":[["chicken breast",300,"g"],["bell pepper",2,"unit"],["onion",1,"unit"],["tortillas",6,"unit"],["avocado",1,"unit"],["lime",1,"unit"],["greek yogurt",100,"g"]],"image":"https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?auto=format&fit=crop&w=1200&q=85"},
 {"id":"chickpea-curry","name":"Creamy Chickpea Curry","description":"Tomato-coconut chickpea curry with spinach and basmati rice.","time":35,"difficulty":"Easy","cost":1.95,"cuisine":"Indian","tags":["Cheap","Vegetarian","Meal Prep"],"image":"https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=85","ingredients":[["chickpeas",400,"g"],["coconut milk",400,"ml"],["tomatoes",300,"g"],["spinach",150,"g"],["onion",1,"unit"],["garlic",2,"cloves"],["curry powder",12,"g"],["rice",160,"g"]]},
 {"id":"beef-bibimbap","name":"Beef Bibimbap","description":"Gochujang beef, rice, carrots, spinach and a fried egg.","time":40,"difficulty":"Medium","cost":4.1,"cuisine":"Korean","tags":["High Protein","Comfort Food"],"ingredients":[["beef mince",300,"g"],["rice",160,"g"],["carrot",2,"unit"],["spinach",150,"g"],["eggs",2,"unit"],["gochujang",30,"g"],["sesame",10,"g"]],"image":"https://images.unsplash.com/photo-1553163147-622ab57be1c7?auto=format&fit=crop&w=1200&q=85"},
 {"id":"med-chicken","name":"Mediterranean Chicken Traybake","description":"Roasted chicken, potatoes, tomatoes, olives and herbs on one tray.","time":45,"difficulty":"Easy","cost":3.4,"cuisine":"Mediterranean","tags":["One-Pot","Meal Prep","High Protein"],"ingredients":[["chicken breast",350,"g"],["potatoes",400,"g"],["tomatoes",250,"g"],["olives",60,"g"],["onion",1,"unit"],["lemon",1,"unit"],["olive oil",20,"ml"]],"image":"https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=1200&q=85"},
 {"id":"lentil-dal","name":"Red Lentil Dal","description":"Fast, warming dal with tomato, spinach and fragrant spices.","time":30,"difficulty":"Easy","cost":1.5,"cuisine":"Indian","tags":["Cheap","Vegetarian","Healthy"],"ingredients":[["red lentils",220,"g"],["tomatoes",250,"g"],["spinach",150,"g"],["onion",1,"unit"],["garlic",2,"cloves"],["coconut milk",200,"ml"],["rice",160,"g"]],"image":"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=85"},
 {"id":"carbonara","name":"Classic Carbonara","description":"Silky egg-and-parmesan pasta with crispy pancetta.","time":20,"difficulty":"Medium","cost":2.65,"cuisine":"Italian","tags":["Comfort Food","Quick"],"ingredients":[["pasta",180,"g"],["pancetta",120,"g"],["eggs",2,"unit"],["parmesan",50,"g"],["black pepper",3,"g"]],"image":"https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1200&q=85"},
 {"id":"german-potato","name":"German Potato Skillet","description":"Crispy potatoes, eggs, onion and herbs in one pan.","time":30,"difficulty":"Easy","cost":1.8,"cuisine":"German","tags":["Cheap","One-Pot","Comfort Food"],"ingredients":[["potatoes",500,"g"],["eggs",3,"unit"],["onion",1,"unit"],["parsley",10,"g"],["olive oil",15,"ml"]],"image":"https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=1200&q=85"},
 {"id":"ceviche","name":"Peruvian-Style Ceviche","description":"Bright lime-marinated fish with red onion, chilli and coriander.","time":20,"difficulty":"Medium","cost":5.2,"cuisine":"Latin American","tags":["Healthy","High Protein"],"ingredients":[["white fish",300,"g"],["lime",4,"unit"],["red onion",1,"unit"],["coriander",15,"g"],["chilli",1,"unit"],["sweet potato",300,"g"]],"image":"https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=85"}
]
