import json
import subprocess
import sys
import time
from pathlib import Path
from urllib.error import HTTPError
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parent
DB = ROOT / "data" / "grocery.db"
AI_DATA = ROOT / "data" / "ai_meals.json"
BASE = "http://127.0.0.1:8011"


def call(method, path, payload=None, expected=200):
    data = None if payload is None else json.dumps(payload).encode()
    req = Request(BASE + path, data=data, method=method, headers={"Content-Type": "application/json"})
    try:
        with urlopen(req, timeout=10) as response:
            body = response.read().decode()
            status = response.status
    except HTTPError as exc:
        status = exc.code
        body = exc.read().decode()
    assert status == expected, f"{method} {path}: expected {expected}, got {status}: {body[:500]}"
    return json.loads(body) if body else None


def wait_for_api():
    for _ in range(40):
        try:
            call("GET", "/api/health")
            return
        except Exception:
            time.sleep(0.25)
    raise RuntimeError("API did not start")


def main():
    if DB.exists(): DB.unlink()
    if AI_DATA.exists(): AI_DATA.unlink()
    # Simulate a meal previously generated by Gemini so startup persistence and
    # the full Discover -> Plan -> Shopping path are tested without an API key.
    AI_DATA.parent.mkdir(parents=True, exist_ok=True)
    AI_DATA.write_text(json.dumps([{
        "id": "ai-qa-taco-bowl",
        "name": "QA Taco Bowl",
        "description": "Persistent AI meal used only by automated QA.",
        "time": 20,
        "difficulty": "Easy",
        "cost": 2.5,
        "cuisine": "Mexican",
        "tags": ["AI Generated", "Quick"],
        "ingredients": [["rice", 160, "g"], ["chicken breast", 250, "g"]],
        "image": "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=85",
        "source": "gemini"
    }]), encoding="utf-8")

    proc = subprocess.Popen(
        [sys.executable, "-m", "uvicorn", "app.main:app", "--host", "127.0.0.1", "--port", "8011"],
        cwd=ROOT, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True,
    )
    try:
        wait_for_api()
        assert call("GET", "/api/health")["ok"] is True

        meals = call("GET", "/api/meals")["meals"]
        meal_ids = {meal["id"] for meal in meals}
        assert len(meals) >= 10
        assert "teriyaki-chicken" in meal_ids
        assert "ai-qa-taco-bowl" in meal_ids, "Persisted AI meal was not loaded into Discover catalog"

        settings = call("GET", "/api/settings")
        assert settings["postcode"] == "13353"
        call("PATCH", "/api/settings", {"postcode": "abc"}, expected=422)
        call("PATCH", "/api/settings", {"postcode": "13353", "shopping_strategy": "best-value"})

        call("POST", "/api/pantry", {"ingredient": "rice", "quantity": 500, "unit": "g"})
        rice = next(row for row in call("GET", "/api/pantry") if row["ingredient"] == "rice")
        assert rice["quantity"] == 500

        call("POST", "/api/events", {"meal_id": "arrabbiata", "action": "dislike"})
        assert any(row["id"] == "arrabbiata" for row in call("GET", "/api/events/dislikes")["meals"])
        call("POST", "/api/events", {"meal_id": "arrabbiata", "action": "undo-dislike"})
        assert not any(row["id"] == "arrabbiata" for row in call("GET", "/api/events/dislikes")["meals"])

        brain = call("POST", "/api/brain-dump", {"prompt": "cheap Mexican dinner, not spicy"})
        assert brain["constraints"]["max_cost"] == 5 and brain["constraints"]["spicy"] is False and brain["mode"] == "mexican"

        plan = call("POST", "/api/plans", {
            "weeks": 1, "servings": 2, "strategy": "best-value", "budget": 40,
            "meal_ids": ["ai-qa-taco-bowl", "teriyaki-chicken", "lentil-dal"]
        })
        assert plan["weeks"] == 1 and plan["budget"] == 40 and len(plan["meals"]) == 7
        assert any(row["meal_id"] == "ai-qa-taco-bowl" for row in plan["meals"]), "AI meal did not integrate into planning"
        planned = plan["meals"][0]
        assert call("PATCH", f"/api/plans/{plan['id']}/meals/{planned['id']}", {"day_index": 3})["day_index"] == 3

        ai_basket = call("POST", "/api/shopping", {
            "meal_ids": ["ai-qa-taco-bowl"], "servings": {"ai-qa-taco-bowl": 2}, "owned": [], "mode": "best-value"
        })
        assert ai_basket["servings"] == 2 and ai_basket["total"] >= 0, "AI meal did not integrate into shopping"

        basket = call("POST", "/api/shopping", {
            "meal_ids": ["teriyaki-chicken"], "servings": {"teriyaki-chicken": 2}, "owned": [], "mode": "best-value"
        })
        assert basket["servings"] == 2 and basket["pantry_savings_items"] >= 1

        eaten = call("POST", "/api/meals/teriyaki-chicken/eaten?servings=2")
        assert any(row["ingredient"] == "rice" for row in eaten["consumed"])
        rice_after = next(row for row in call("GET", "/api/pantry") if row["ingredient"] == "rice")
        assert rice_after["quantity"] == 340

        rewe_status = call("GET", "/api/rewe/status")
        assert rewe_status["live_data"] is False and rewe_status["data_freshness"] == "catalog_snapshot"

        print("QA PASS: core loop + persistent AI meal Discover/Plan/Shopping integration + REWE status")
    finally:
        proc.terminate()
        try: proc.wait(timeout=5)
        except subprocess.TimeoutExpired: proc.kill()
        if AI_DATA.exists(): AI_DATA.unlink()
        if proc.returncode not in (0, -15, None) and proc.stdout: print(proc.stdout.read())


if __name__ == "__main__":
    main()
