PRODUCTS = [
 {"ingredient":"chicken breast","name":"REWE Beste Wahl Hähnchenbrustfilet","brand":"REWE Beste Wahl","pack_qty":500,"unit":"g","price":5.49,"unit_price":10.98,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"rice","name":"REWE Beste Wahl Langkornreis","brand":"REWE Beste Wahl","pack_qty":1000,"unit":"g","price":1.79,"unit_price":1.79,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"pasta","name":"ja! Spaghetti","brand":"ja!","pack_qty":500,"unit":"g","price":0.89,"unit_price":1.78,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"tomatoes","name":"Cherry Rispentomaten","brand":"REWE","pack_qty":500,"unit":"g","price":1.99,"unit_price":3.98,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"spinach","name":"REWE Bio Blattspinat","brand":"REWE Bio","pack_qty":450,"unit":"g","price":2.49,"unit_price":5.53,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"onion","name":"Speisezwiebeln","brand":"REWE","pack_qty":1000,"unit":"g","price":1.49,"unit_price":1.49,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"garlic","name":"Knoblauch","brand":"REWE","pack_qty":1,"unit":"bulb","price":0.69,"unit_price":0.69,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"cucumber","name":"Gurke","brand":"REWE Regional","pack_qty":1,"unit":"unit","price":0.89,"unit_price":0.89,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"avocado","name":"Avocado essreif","brand":"REWE","pack_qty":1,"unit":"unit","price":1.29,"unit_price":1.29,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"bell pepper","name":"Paprika Mix","brand":"REWE","pack_qty":3,"unit":"unit","price":2.49,"unit_price":0.83,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"tortillas","name":"REWE Beste Wahl Weizen Tortillas","brand":"REWE Beste Wahl","pack_qty":6,"unit":"unit","price":1.59,"unit_price":0.27,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"greek yogurt","name":"REWE Bio Griechischer Joghurt","brand":"REWE Bio","pack_qty":500,"unit":"g","price":1.99,"unit_price":3.98,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"eggs","name":"REWE Bio Eier","brand":"REWE Bio","pack_qty":10,"unit":"unit","price":3.29,"unit_price":0.33,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"feta","name":"Patros Feta","brand":"Patros","pack_qty":180,"unit":"g","price":2.19,"unit_price":12.17,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"bread","name":"REWE Beste Wahl Bauernbrot","brand":"REWE Beste Wahl","pack_qty":500,"unit":"g","price":1.89,"unit_price":3.78,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"chickpeas","name":"REWE Bio Kichererbsen","brand":"REWE Bio","pack_qty":400,"unit":"g","price":1.19,"unit_price":2.98,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"coconut milk","name":"REWE Beste Wahl Kokosmilch","brand":"REWE Beste Wahl","pack_qty":400,"unit":"ml","price":1.29,"unit_price":3.23,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"red lentils","name":"REWE Beste Wahl Rote Linsen","brand":"REWE Beste Wahl","pack_qty":500,"unit":"g","price":1.69,"unit_price":3.38,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"parmesan","name":"Parmigiano Reggiano","brand":"REWE","pack_qty":150,"unit":"g","price":3.49,"unit_price":23.27,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"pancetta","name":"Pancetta","brand":"REWE","pack_qty":100,"unit":"g","price":2.49,"unit_price":24.90,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"potatoes","name":"Speisekartoffeln","brand":"REWE Regional","pack_qty":2500,"unit":"g","price":2.99,"unit_price":1.20,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"salmon","name":"Norwegisches Lachsfilet","brand":"REWE","pack_qty":300,"unit":"g","price":6.99,"unit_price":23.30,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"edamame","name":"REWE Beste Wahl Edamame","brand":"REWE Beste Wahl","pack_qty":300,"unit":"g","price":2.49,"unit_price":8.30,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"lime","name":"Limetten","brand":"REWE","pack_qty":3,"unit":"unit","price":1.79,"unit_price":0.60,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"olive oil","name":"REWE Bio Olivenöl","brand":"REWE Bio","pack_qty":500,"unit":"ml","price":5.99,"unit_price":11.98,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"soy sauce","name":"Kikkoman Sojasauce","brand":"Kikkoman","pack_qty":150,"unit":"ml","price":2.79,"unit_price":18.60,"url":"https://www.rewe.de/shop/"},
 {"ingredient":"sesame","name":"Sesam","brand":"REWE Beste Wahl","pack_qty":100,"unit":"g","price":1.49,"unit_price":14.90,"url":"https://www.rewe.de/shop/"},
]
